<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>RoboForge.Shared.Domain.UnitTests</RootNamespace>
    <AssemblyName>RoboForge.Shared.Domain.UnitTests</AssemblyName>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.MTP" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Shouldly" />
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Shared\Shared.Domain\Shared.Domain.csproj" />
  </ItemGroup>

</Project>
