<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>RoboForge.Shared.UI</RootNamespace>
    <AssemblyName>RoboForge.Shared.UI</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Ardalis.GuardClauses" />
  </ItemGroup>

</Project>
